### ISSUE TITLE
三分应采用固定迭代次数的写法

### ISSUE THREAD

**Issue by wlbksy** [BengbuGuards/StarLocator#1]
https://github.com/BengbuGuards/StarLocator/blob/8b28b7c12a4239992a1bd44f2743ec2a53f4e7e5/core/math.js#L121

不建议采用误差写法，建议采用迭代固定次数的写法。浮点数的误差可能会遇到坑，不收敛，导致死循环。事实上，js 的浮点数是 64位，60次循环，已经可以把 1e9 范围内的二分、三分误差降为 1e-9 以下了

**Comment by Hiroshi1993** [comment]
这个问题我不熟悉，听大家的。

**Comment by cheanus** [comment]
我把两个截止条件用个“或”结合起来吧
