### ISSUE TITLE
平面方程看的头大

### ISSUE THREAD

**Issue by wlbksy** [BengbuGuards/StarLocator#2]
js 有算伪逆的东西 ，不到200k, https://mathjs.org/docs/reference/functions/pinv.html

**Comment by wlbksy** [comment]
思路：
1. 算出各个星星对应的地面的gp经纬度之后，把这些 gp 转成单位球面上的三维坐标  (x,y,z)。这样有 n 个 gp 点，就是 n 个向量。
2. 每个向量和目标点的向量的点乘就是对应的天顶角的余弦。点乘就是线性方程，因此就构成了 n 个线性方程 Ax=y 。方程的 A 的每i 行是第 i 个 gp 点的 (x,y,z)。方程的y这个列向量的第 i 个元素，就是 第 i 个天顶角的余弦。方程的 x 就是目标点的 (x,y,z) 的列向量
3. 用 伪逆解出方程的 x，即解出目标点的 (x,y,z)，这是目标点的单位球面上的三维坐标，把它转换成经纬度，就是答案

我看代码里面有去处outlier 的逻辑，这个预处理，应该也能让伪逆的结果更好

**Comment by Hiroshi1993** [comment]
这个方案可用，而且说不定精度比目前的平方倒数加权更高。列入计划中。

**Comment by wlbksy** [comment]
使用所有星星的数据，计算伪逆得可以得到一个结果。

如果界面允许的话，可以选择所有星星的一个子集，即用哪几个星星去算伪逆。这些不同的选择，应该也会给出不同的结果。把这些结果也显示在界面上，便于用户直观的了解哪个星星带来的误差比较大。这样就可以勾选最终用于计算的星星子集，来计算最后的结果

**Comment by BengbuGuards** [comment]
加大了操作难度

**Comment by cheanus** [comment]
截止目前，我们在3个测例上的实验显示，伪逆相比中位数法，虽然在一般情况下误差能比中位数法低点，但对噪点的鲁棒性不足，最终导致平均误差较大。
选择多种星星子集来计算是一种避免噪声干扰的方式，但要评价这多个结果的准确性（这一步按理不应该让用户来完成），又不免落回“平均”“中位数”等操作上，显得该算法相比中位数来说更加繁琐。
总之，在没有其他优势上，我们暂时还是考虑使用目前的中位数法来计算最终位置。
